# Generated by Django 3.2.5 on 2021-11-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_otp_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='securityans',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='cards',
            name='securityquestion',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
