# Generated by Django 3.2.5 on 2021-11-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_auto_20211103_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='email',
            field=models.EmailField(default='parvg555@gmail.com', max_length=254),
        ),
    ]
