# Generated by Django 3.2.5 on 2021-11-05 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0004_cards_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='otp',
            name='Expire_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 15, 47, 7, 762924)),
        ),
    ]
