# Generated by Django 3.2.5 on 2021-11-05 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_auto_20211105_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='cardnumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otp',
            name='Expire_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 16, 42, 11, 161290)),
        ),
    ]
