# Generated by Django 3.2.5 on 2021-11-05 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0008_alter_otp_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='Expire_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 16, 52, 43, 565155)),
        ),
    ]
