# Generated by Django 3.2.5 on 2021-11-05 15:40

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otp', '0011_alter_otp_expire_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trasactions',
            new_name='Trasaction',
        ),
        migrations.AlterField(
            model_name='otp',
            name='Expire_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 21, 14, 57, 448537)),
        ),
    ]
