# Generated by Django 3.2.5 on 2021-11-05 15:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0012_auto_20211105_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trasaction',
            name='user',
        ),
        migrations.AddField(
            model_name='trasaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otp.cards'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='Expire_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 21, 23, 25, 992453)),
        ),
    ]
